
// This is a personal academic project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++, C#, and Java: https://pvs-studio.com

package juliet.testcases.CWE643_Xpath_Injection;

import juliet.support.AbstractTestCase;
import juliet.support.IO;

public class Main {

	public static void main(String[] args) {
		
		if(args.length != 0) {
		
			if(args[0].equals("-h") || args[0].equals("--help")) {
		
				System.err.println("To use this main, you can either run the program with no " +
				"command line arguments to run all test cases or you can specify one or more classes to test");
				System.err.println("For example:");
				System.err.println("java juliet.support.Main juliet.testcases.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference.custom_function.CWE690_Unchecked_Return_Value_to_NULL_Pointer_Dereference__custom_function_01 juliet.testcases.CWE481_Assigning_instead_of_Comparing.bool.CWE481_Assigning_instead_of_Comparing__bool_01");
				System.exit(1);
			}
			
			/* User supplied some class names on the command line, just use those with introspection
			 *
			 * String classNames[] = { "CWE481_Assigning_instead_of_Comparing__boolean_01",
			 *		"CWE476_Null_Pointer_Dereference__getProperty_01" };
 			 * could read class names from command line or use
			 * http://sadun-util.sourceforge.net/api/org/sadun/util/
			 * ClassPackageExplorer.html
			 */

			for (String className : args) {

				try {
					
					/* String classNameWithPackage = "testcases." + className; */
					
					/* IO.writeLine("classNameWithPackage = " + classNameWithPackage); */

					Class<?> myClass = Class.forName(className);

					AbstractTestCase myObject = (AbstractTestCase) myClass
							.newInstance();

					myObject.runTest(className);

				} catch (Exception ex) {

					IO.writeLine("Could not run test for class " + className);
					ex.printStackTrace();

				}
				
				IO.writeLine(""); /* leave a blank line between classes */

			}

		} else {
		
			/* No command line args were used, we want to run every testcase */
			
			/* needed to separate these calls into other methods because
			   we were running into the size limit Java has for a single method */
			runTestCWE1();
			runTestCWE2();
			runTestCWE3();
			runTestCWE4();
			runTestCWE5();
			runTestCWE6();
			runTestCWE7();
			runTestCWE8();
			runTestCWE9();
		}			
	}

private static void runTestCWE1() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-1 */

			/* END-AUTOGENERATED-JAVA-TESTS-1 */
}

private static void runTestCWE2() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-2 */

			/* END-AUTOGENERATED-JAVA-TESTS-2 */
}

private static void runTestCWE3() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-3 */

			/* END-AUTOGENERATED-JAVA-TESTS-3 */
}

private static void runTestCWE4() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-4 */

			/* END-AUTOGENERATED-JAVA-TESTS-4 */
}

private static void runTestCWE5() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-5 */

			/* END-AUTOGENERATED-JAVA-TESTS-5 */
}

private static void runTestCWE6() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-6 */
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__connect_tcp_01()).runTest("CWE643_Xpath_Injection__connect_tcp_01");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__connect_tcp_02()).runTest("CWE643_Xpath_Injection__connect_tcp_02");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__connect_tcp_03()).runTest("CWE643_Xpath_Injection__connect_tcp_03");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__connect_tcp_04()).runTest("CWE643_Xpath_Injection__connect_tcp_04");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__connect_tcp_05()).runTest("CWE643_Xpath_Injection__connect_tcp_05");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__connect_tcp_06()).runTest("CWE643_Xpath_Injection__connect_tcp_06");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__connect_tcp_07()).runTest("CWE643_Xpath_Injection__connect_tcp_07");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__connect_tcp_08()).runTest("CWE643_Xpath_Injection__connect_tcp_08");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__connect_tcp_09()).runTest("CWE643_Xpath_Injection__connect_tcp_09");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__connect_tcp_10()).runTest("CWE643_Xpath_Injection__connect_tcp_10");
			
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__console_readLine_01()).runTest("CWE643_Xpath_Injection__console_readLine_01");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__console_readLine_02()).runTest("CWE643_Xpath_Injection__console_readLine_02");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__console_readLine_03()).runTest("CWE643_Xpath_Injection__console_readLine_03");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__console_readLine_04()).runTest("CWE643_Xpath_Injection__console_readLine_04");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__console_readLine_05()).runTest("CWE643_Xpath_Injection__console_readLine_05");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__console_readLine_06()).runTest("CWE643_Xpath_Injection__console_readLine_06");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__console_readLine_07()).runTest("CWE643_Xpath_Injection__console_readLine_07");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__console_readLine_08()).runTest("CWE643_Xpath_Injection__console_readLine_08");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__console_readLine_09()).runTest("CWE643_Xpath_Injection__console_readLine_09");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__console_readLine_10()).runTest("CWE643_Xpath_Injection__console_readLine_10");
			
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__database_01()).runTest("CWE643_Xpath_Injection__database_01");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__database_02()).runTest("CWE643_Xpath_Injection__database_02");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__database_03()).runTest("CWE643_Xpath_Injection__database_03");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__database_04()).runTest("CWE643_Xpath_Injection__database_04");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__database_05()).runTest("CWE643_Xpath_Injection__database_05");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__database_06()).runTest("CWE643_Xpath_Injection__database_06");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__database_07()).runTest("CWE643_Xpath_Injection__database_07");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__database_08()).runTest("CWE643_Xpath_Injection__database_08");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__database_09()).runTest("CWE643_Xpath_Injection__database_09");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__database_10()).runTest("CWE643_Xpath_Injection__database_10");
			
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Environment_01()).runTest("CWE643_Xpath_Injection__Environment_01");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Environment_02()).runTest("CWE643_Xpath_Injection__Environment_02");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Environment_03()).runTest("CWE643_Xpath_Injection__Environment_03");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Environment_04()).runTest("CWE643_Xpath_Injection__Environment_04");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Environment_05()).runTest("CWE643_Xpath_Injection__Environment_05");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Environment_06()).runTest("CWE643_Xpath_Injection__Environment_06");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Environment_07()).runTest("CWE643_Xpath_Injection__Environment_07");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Environment_08()).runTest("CWE643_Xpath_Injection__Environment_08");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Environment_09()).runTest("CWE643_Xpath_Injection__Environment_09");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Environment_10()).runTest("CWE643_Xpath_Injection__Environment_10");
			
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__File_01()).runTest("CWE643_Xpath_Injection__File_01");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__File_02()).runTest("CWE643_Xpath_Injection__File_02");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__File_03()).runTest("CWE643_Xpath_Injection__File_03");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__File_04()).runTest("CWE643_Xpath_Injection__File_04");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__File_05()).runTest("CWE643_Xpath_Injection__File_05");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__File_06()).runTest("CWE643_Xpath_Injection__File_06");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__File_07()).runTest("CWE643_Xpath_Injection__File_07");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__File_08()).runTest("CWE643_Xpath_Injection__File_08");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__File_09()).runTest("CWE643_Xpath_Injection__File_09");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__File_10()).runTest("CWE643_Xpath_Injection__File_10");
			
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__listen_tcp_01()).runTest("CWE643_Xpath_Injection__listen_tcp_01");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__listen_tcp_02()).runTest("CWE643_Xpath_Injection__listen_tcp_02");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__listen_tcp_03()).runTest("CWE643_Xpath_Injection__listen_tcp_03");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__listen_tcp_04()).runTest("CWE643_Xpath_Injection__listen_tcp_04");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__listen_tcp_05()).runTest("CWE643_Xpath_Injection__listen_tcp_05");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__listen_tcp_06()).runTest("CWE643_Xpath_Injection__listen_tcp_06");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__listen_tcp_07()).runTest("CWE643_Xpath_Injection__listen_tcp_07");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__listen_tcp_08()).runTest("CWE643_Xpath_Injection__listen_tcp_08");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__listen_tcp_09()).runTest("CWE643_Xpath_Injection__listen_tcp_09");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__listen_tcp_10()).runTest("CWE643_Xpath_Injection__listen_tcp_10");
			
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__PropertiesFile_01()).runTest("CWE643_Xpath_Injection__PropertiesFile_01");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__PropertiesFile_02()).runTest("CWE643_Xpath_Injection__PropertiesFile_02");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__PropertiesFile_03()).runTest("CWE643_Xpath_Injection__PropertiesFile_03");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__PropertiesFile_04()).runTest("CWE643_Xpath_Injection__PropertiesFile_04");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__PropertiesFile_05()).runTest("CWE643_Xpath_Injection__PropertiesFile_05");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__PropertiesFile_06()).runTest("CWE643_Xpath_Injection__PropertiesFile_06");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__PropertiesFile_07()).runTest("CWE643_Xpath_Injection__PropertiesFile_07");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__PropertiesFile_08()).runTest("CWE643_Xpath_Injection__PropertiesFile_08");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__PropertiesFile_09()).runTest("CWE643_Xpath_Injection__PropertiesFile_09");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__PropertiesFile_10()).runTest("CWE643_Xpath_Injection__PropertiesFile_10");
			
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Property_01()).runTest("CWE643_Xpath_Injection__Property_01");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Property_02()).runTest("CWE643_Xpath_Injection__Property_02");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Property_03()).runTest("CWE643_Xpath_Injection__Property_03");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Property_04()).runTest("CWE643_Xpath_Injection__Property_04");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Property_05()).runTest("CWE643_Xpath_Injection__Property_05");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Property_06()).runTest("CWE643_Xpath_Injection__Property_06");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Property_07()).runTest("CWE643_Xpath_Injection__Property_07");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Property_08()).runTest("CWE643_Xpath_Injection__Property_08");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Property_09()).runTest("CWE643_Xpath_Injection__Property_09");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__Property_10()).runTest("CWE643_Xpath_Injection__Property_10");
			
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__URLConnection_01()).runTest("CWE643_Xpath_Injection__URLConnection_01");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__URLConnection_02()).runTest("CWE643_Xpath_Injection__URLConnection_02");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__URLConnection_03()).runTest("CWE643_Xpath_Injection__URLConnection_03");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__URLConnection_04()).runTest("CWE643_Xpath_Injection__URLConnection_04");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__URLConnection_05()).runTest("CWE643_Xpath_Injection__URLConnection_05");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__URLConnection_06()).runTest("CWE643_Xpath_Injection__URLConnection_06");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__URLConnection_07()).runTest("CWE643_Xpath_Injection__URLConnection_07");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__URLConnection_08()).runTest("CWE643_Xpath_Injection__URLConnection_08");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__URLConnection_09()).runTest("CWE643_Xpath_Injection__URLConnection_09");
			(new juliet.testcases.CWE643_Xpath_Injection.CWE643_Xpath_Injection__URLConnection_10()).runTest("CWE643_Xpath_Injection__URLConnection_10");
			
			/* END-AUTOGENERATED-JAVA-TESTS-6 */
}

private static void runTestCWE7() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-7 */

			/* END-AUTOGENERATED-JAVA-TESTS-7 */
}

private static void runTestCWE8() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-8 */

			/* END-AUTOGENERATED-JAVA-TESTS-8 */
}

private static void runTestCWE9() {
/* BEGIN-AUTOGENERATED-JAVA-TESTS-9 */

			/* END-AUTOGENERATED-JAVA-TESTS-9 */
}
}